spring.application.name=desafio2

# Database Connection URL
spring.datasource.url=${DB_URL}

# Database Credentials
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# MySQL JDBC Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
